
spring:
  application:
    name: notifservice

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: notification-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 9090
twilio:
  account-sid: "ACc7dafa72520c031aa2fb7f5ce3cbfd71"  # From Twilio Dashboard
  auth-token: "fa3875048b5f9d79961f57ea7e62d33a"              # From Twilio Dashboard
  phone-number: "+13136310647"