apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: banking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          # Replace with your actual ECR Image URI
          image: 342547628532.dkr.ecr.us-west-2.amazonaws.com/ebanking:notif-latest
          ports:
            - containerPort: 9090
          env:
            # 1. SERVER CONFIG
            - name: SERVER_PORT
              value: "9090"

            # 2. KAFKA CONNECTION
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "notification-group"

            # 3. TWILIO CONFIGURATION (SECURE)
            # Instead of 'value', we use 'valueFrom' -> 'secretKeyRef'
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: twilio-account-sid

            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: twilio-auth-token

            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: twilio-phone-number

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: banking-ns
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - port: 80           # Exposed Port
      targetPort: 9090   # Container Port